In [27]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np


# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [28]:
datos = pd.read_csv('Datos/datos_empresa.csv', index_col=0)
datos_limpios = pd.read_csv('Datos/datos_empresa_V1.csv', index_col=0)


In [29]:
#Creamos Dataframe de las columnas de los df a comparar

datos_col = pd.DataFrame(list(datos.columns), columns=['datos'])
datos_col
datos_limpio_col = pd.DataFrame(list(datos_limpios.columns), columns=['datos2'])
datos_limpio_col


datos2
0                        Age
1                  Attrition
2             BusinessTravel
3                  DailyRate
4                 Department
5           DistanceFromHome
6                  Education
7             EducationField
8             employeenumber
9    EnvironmentSatisfaction
10                    Gender
11                HourlyRate
12            JobInvolvement
13                  JobLevel
14                   JobRole
15           JobSatisfaction
16             MaritalStatus
17             MonthlyIncome
18               MonthlyRate
19        NUMCOMPANIESWORKED
20                  OverTime
21         PercentSalaryHike
22         PerformanceRating
23  RelationshipSatisfaction
24             StandardHours
25          StockOptionLevel
26         TOTALWORKINGYEARS
27     TrainingTimesLastYear
28           WORKLIFEBALANCE
29            YearsAtCompany
30        YearsInCurrentRole
31   YearsSinceLastPromotion
32      YEARSWITHCURRMANAGER
33                 DateBirth
34                RemoteWork

In [30]:
# mergeamos las columnas para saber si tenemos duplicados

df_merge = datos_col.merge(datos_limpio_col, left_on='datos', right_on='datos2', how = 'left')
df_merge




datos                    datos2
0                        Age                       Age
1                  Attrition                 Attrition
2             BusinessTravel            BusinessTravel
3                  DailyRate                 DailyRate
4                 Department                Department
5           DistanceFromHome          DistanceFromHome
6                  Education                 Education
7             EducationField            EducationField
8              employeecount                       NaN
9             employeenumber            employeenumber
10   EnvironmentSatisfaction   EnvironmentSatisfaction
11                    Gender                    Gender
12                HourlyRate                HourlyRate
13            JobInvolvement            JobInvolvement
14                  JobLevel                  JobLevel
15                   JobRole                   JobRole
16           JobSatisfaction           JobSatisfaction
17             MaritalStatus             MaritalStatus
18             MonthlyIncome             MonthlyIncome
19               MonthlyRate               MonthlyRate
20        NUMCOMPANIESWORKED        NUMCOMPANIESWORKED
21                    Over18                       NaN
22                  OverTime                  OverTime
23         PercentSalaryHike         PercentSalaryHike
24         PerformanceRating         PerformanceRating
25  RelationshipSatisfaction  RelationshipSatisfaction
26             StandardHours             StandardHours
27          StockOptionLevel          StockOptionLevel
28         TOTALWORKINGYEARS         TOTALWORKINGYEARS
29     TrainingTimesLastYear     TrainingTimesLastYear
30           WORKLIFEBALANCE           WORKLIFEBALANCE
31            YearsAtCompany            YearsAtCompany
32        YearsInCurrentRole        YearsInCurrentRole
33   YearsSinceLastPromotion   YearsSinceLastPromotion
34      YEARSWITHCURRMANAGER      YEARSWITHCURRMANAGER
35       SameAsMonthlyIncome                       NaN
36                 DateBirth                 DateBirth
37                    Salary                       NaN
38           RoleDepartament                       NaN
39            NUMBERCHILDREN                       NaN
40                RemoteWork                RemoteWork

In [31]:
#filtro para saber columnas que habíamos borrado

filtro = df_merge['datos2'].isna()
df_filtro = df_merge[filtro]

df_filtro

datos datos2
8         employeecount    NaN
21               Over18    NaN
35  SameAsMonthlyIncome    NaN
37               Salary    NaN
38      RoleDepartament    NaN
39       NUMBERCHILDREN    NaN

In [32]:
comparacion = df_merge['datos'] == df_merge['datos2']
comparacion

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21    False
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35    False
36     True
37    False
38    False
39    False
40     True
dtype: bool

In [33]:
#borramos columnas que no necesitamos

datos.drop( columns = ['employeecount','Over18','SameAsMonthlyIncome', 'Salary', 'RoleDepartament', 'NUMBERCHILDREN'], inplace= True)

In [34]:
# transformamos columnas para su mejor visulatización las convertimos todos a lower

new_columns = {column : column.lower() for column in datos}

new_columns

datos.rename(columns = new_columns, inplace= True)

datos.head()

age attrition businesstravel dailyrate                department  \
0  51        No            NaN    684,0$                       NaN   
1  52        No            NaN    699,0$                       NaN   
2  42        No  travel_rarely    532,0$   Research & Development    
3  47        No  travel_rarely    359,0$                       NaN   
4  46        No            NaN   1319,0$                       NaN   

   distancefromhome  education    educationfield employeenumber  \
0                 6          3               NaN          162,0   
1                 1          4     Life Sciences          259,0   
2                 4          2  Technical Degree          319,0   
3                 2          4           Medical            NaN   
4                 3          3  Technical Degree            NaN   

   environmentsatisfaction  gender hourlyrate  jobinvolvement  joblevel  \
0                        1       0         51               3         5   
1                        3       0         65               2         5   
2                        3       0         58               3         5   
3                        1       1         82               3         4   
4                        1       1         45               4         4   

               jobrole  jobsatisfaction maritalstatus monthlyincome  \
0   resEArch DIREcToR                 3           NaN       19537,0   
1             ManAGeR                 3           NaN       19999,0   
2             ManaGER                 4       Married       19232,0   
3   ReseArCH DIrECtOr                 3       Married       17169,0   
4     sAleS EXECUtIve                 1      Divorced           NaN   

   monthlyrate  numcompaniesworked overtime  percentsalaryhike  \
0         6462                   7       No                 13   
1         5678                   0      NaN                 14   
2         4933                   1       No                 11   
3        26703                   3      NaN                 19   
4         7739                   2       No                 12   

  performancerating  relationshipsatisfaction standardhours  stockoptionlevel  \
0               3,0                         3           NaN                 0   
1               3,0                         1           NaN                 1   
2               3,0                         4           NaN                 0   
3               3,0                         2           NaN                 2   
4               3,0                         4           NaN                 1   

  totalworkingyears  trainingtimeslastyear worklifebalance  yearsatcompany  \
0               NaN                      5             3,0              20   
1              34,0                      5             3,0              33   
2              22,0                      3             NaN              22   
3               NaN                      2             NaN              20   
4               NaN                      5             3,0              19   

  yearsincurrentrole  yearssincelastpromotion  yearswithcurrmanager  \
0                NaN                       15                    15   
1                NaN                       11                     9   
2                NaN                       11                    15   
3                NaN                        5                     6   
4                NaN                        2                     8   

   datebirth remotework  
0       1972        Yes  
1       1971          1  
2       1981          1  
3       1976      False  
4       1977          0

In [35]:
# Transformamos columnas

In [36]:
datos['age'].unique()

age = datos['age'].str.replace('fifty-eight', '58 ').str.replace('fifty-eight', '47 ').str.replace('thirty-six', '36').str.replace('fifty-five', '55').str.replace('fifty-two', '52').str.replace('thirty-one', '31').str.replace('twenty-six', '36').str.replace('thirty-seven', '37').str.replace('thirty-seven', '37').str.replace('thirty-two', '32').str.replace('twenty-four', '24').str.replace('forty-seven', '47').str.replace('thirty', '30')

datos['age'] = age

datos['age'].unique()

array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', '53', '43', '60', '32',
       '37', '49', '39', '50', '44', '30', '58 ', '29', '31', '54', '57',
       '27', '28', '26', '25', '24', '23', '22', '21', '20', '19', '18'],
      dtype=object)

In [37]:
datos['attrition'].unique()

array(['No', 'Yes'], dtype=object)

In [38]:
businesstravel = datos['businesstravel'].str.replace('_', ' ').str.replace('-', ' ').str.capitalize()

datos['businesstravel'] = businesstravel

datos['businesstravel'].unique()



array([nan, 'Travel rarely', 'Travel frequently', 'Non travel'],
      dtype=object)

In [39]:
# nos falta ver qué hacemos con los Nan y convertirlo en INT

dailyrate = datos['dailyrate'].str.replace('$', '')


datos['dailyrate'] = dailyrate

datos['dailyrate'] 




0        684,0
1        699,0
2        532,0
3        359,0
4       1319,0
         ...  
1609     530,0
1610     805,0
1611     903,0
1612    1229,0
1613     566,0
Name: dailyrate, Length: 1614, dtype: object

In [40]:
# ver qué hacemos con los Nan

datos['department'].unique()

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [42]:
#numeros negativos

datos['distancefromhome'].unique()

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44], dtype=int64)

In [43]:
# overtime mirar qué hacer con los nan

datos['overtime'].unique()

array(['No', nan, 'Yes'], dtype=object)

In [44]:
datos['percentsalaryhike'].unique()

suma = datos['percentsalaryhike'].value_counts()
suma

percentsalaryhike
11    232
13    230
12    225
14    220
15    110
18     98
17     88
16     86
19     82
20     60
22     59
21     51
23     29
24     25
25     19
Name: count, dtype: int64

In [46]:
#mirar que hacer con los nan y convertir a número porque es un objeto por las comas

suma = datos['performancerating'].value_counts()
print(suma)

performancerating = datos['performancerating'].str.replace(',0', '')


datos['performancerating'] = performancerating

datos['performancerating'] 



performancerating
3    1205
4     214
Name: count, dtype: int64


0         3
1         3
2         3
3         3
4         3
       ... 
1609    NaN
1610      3
1611      3
1612    NaN
1613      3
Name: performancerating, Length: 1614, dtype: object

In [47]:
# No hacemos cambios de momento

datos['relationshipsatisfaction'].unique()



array([3, 1, 4, 2], dtype=int64)

In [48]:
#borramos standard hours porque no tiene sentido tiene muchos nan y 80h es imposible
datos.drop( columns = ['standardhours'], inplace= True)




In [49]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'remotework'],
      dtype='object')

In [50]:
# No he hecho nada en esta columna parece estra bien
datos['stockoptionlevel'].unique()

array([0, 1, 2, 3], dtype=int64)

In [51]:
# En cuanto gestionemos los nan cambiar a INT

datos['totalworkingyears'].unique()

totalworkingyears = datos['totalworkingyears'].str.replace(',0', '')


datos['totalworkingyears'] = totalworkingyears

datos['totalworkingyears'] 


0       NaN
1        34
2        22
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611      9
1612     12
1613    NaN
Name: totalworkingyears, Length: 1614, dtype: object

In [52]:
# En cuanto gestionemos los nan cambiar a INT

datos['totalworkingyears'].unique()

array([nan, '34', '22', '28', '20', '21', '33', '40', '18', '25', '15',
       '17', '26', '16', '24', '14', '23', '27', '19', '11', '38', '37',
       '13', '12', '29', '10', '36', '35', '9', '31', '32', '8', '7',
       '30', '6', '5', '4', '3', '2', '1', '0'], dtype=object)

In [53]:
# trainingtimeslastyear no hacer nada aparentemente toda la información es correcta

datos['trainingtimeslastyear'].unique()



array([5, 3, 2, 0, 1, 4, 6], dtype=int64)

In [54]:
# Ver qué hacemos con los NaN y convertir a INT

datos['worklifebalance'].unique()

worklifebalance = datos['worklifebalance'].str.replace(',0', '')


datos['worklifebalance'] = worklifebalance

datos['worklifebalance'] 


0         3
1         3
2       NaN
3       NaN
4         3
       ... 
1609      3
1610      2
1611      3
1612      3
1613      3
Name: worklifebalance, Length: 1614, dtype: object

In [55]:
# todo aparenta estar correcto

datos['yearsatcompany'].unique()



array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [56]:
# Ver qué hacemos con los NaN y convertir a INT creo que esta la tendremos que borrar porque no hay casi datos

datos['yearsincurrentrole'].unique()

yearsincurrentrole = datos['yearsincurrentrole'].str.replace(',0', '')


datos['yearsincurrentrole'] = yearsincurrentrole

datos['yearsincurrentrole'] 





0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611    NaN
1612    NaN
1613    NaN
Name: yearsincurrentrole, Length: 1614, dtype: object

In [57]:
datos['yearssincelastpromotion'].unique()




datos[['yearssincelastpromotion']]


yearssincelastpromotion
0                          15
1                          11
2                          11
3                           5
4                           2
...                       ...
1609                        3
1610                        0
1611                        0
1612                        0
1613                        0

[1614 rows x 1 columns]

In [58]:
# no tenemos que tocar nada

datos['yearswithcurrmanager'].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [59]:
# esta ok

datos['datebirth'].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005],
      dtype=int64)

In [60]:
#Tendremos que ver qué hacemos con los Nan

datos['remotework'].unique()
    


array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [61]:
diccionario_mapa = {'Yes':'Yes', '1':'Yes', 'False':'No', '0':'No', 'True':'Yes'}

datos["remotework"] = datos["remotework"].map(diccionario_mapa)

datos['remotework'].unique()

array(['Yes', 'No'], dtype=object)

In [62]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'remotework'],
      dtype='object')