In [43]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np


# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames
pd.set_option('display.max_colwidth', None) # para visualizar todo el contenido de los valores
pd.set_option('display.max_rows', None) # Para visualizar todo el contenido de las filas

In [ ]:
# overtime mirar qué hacer con los nan

datos['overtime'].unique()

array(['No', nan, 'Yes'], dtype=object)

In [ ]:
datos['percentsalaryhike'].unique()



array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18],
      dtype=int64)

In [ ]:
#mirar que hacer con los nan y convertir a número porque es un objeto por las comas

suma = datos['performancerating'].value_counts()
print(suma)

performancerating = datos['performancerating'].str.replace(',0', '')


datos['performancerating'] = performancerating

datos['performancerating'] 



performancerating
3    1205
4     214
Name: count, dtype: int64


0         3
1         3
2         3
3         3
4         3
       ... 
1609    NaN
1610      3
1611      3
1612    NaN
1613      3
Name: performancerating, Length: 1614, dtype: object

In [ ]:
# No hacemos cambios de momento

datos['relationshipsatisfaction'].unique()



array([3, 1, 4, 2], dtype=int64)

In [ ]:
#borramos standard hours porque no tiene sentido tiene muchos nan y 80h es imposible
datos.drop( columns = ['standardhours'], inplace= True)




In [ ]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'remotework'],
      dtype='object')

In [ ]:
# No he hecho nada en esta columna parece estra bien
datos['stockoptionlevel'].unique()

array([0, 1, 2, 3], dtype=int64)

In [ ]:
# En cuanto gestionemos los nan cambiar a INT

datos['totalworkingyears'].unique()

totalworkingyears = datos['totalworkingyears'].str.replace(',0', '')


datos['totalworkingyears'] = totalworkingyears

datos['totalworkingyears'] 


0       NaN
1        34
2        22
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611      9
1612     12
1613    NaN
Name: totalworkingyears, Length: 1614, dtype: object

In [ ]:
# En cuanto gestionemos los nan cambiar a INT

datos['totalworkingyears'].unique()

array([nan, '34', '22', '28', '20', '21', '33', '40', '18', '25', '15',
       '17', '26', '16', '24', '14', '23', '27', '19', '11', '38', '37',
       '13', '12', '29', '10', '36', '35', '9', '31', '32', '8', '7',
       '30', '6', '5', '4', '3', '2', '1', '0'], dtype=object)

In [ ]:
# trainingtimeslastyear no hacer nada aparentemente toda la información es correcta

datos['trainingtimeslastyear'].unique()



array([5, 3, 2, 0, 1, 4, 6], dtype=int64)

In [ ]:
# Ver qué hacemos con los NaN y convertir a INT

datos['worklifebalance'].unique()

worklifebalance = datos['worklifebalance'].str.replace(',0', '')


datos['worklifebalance'] = worklifebalance

datos['worklifebalance'] 


0         3
1         3
2       NaN
3       NaN
4         3
       ... 
1609      3
1610      2
1611      3
1612      3
1613      3
Name: worklifebalance, Length: 1614, dtype: object

In [ ]:
# todo aparenta estar correcto

datos['yearsatcompany'].unique()



array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [ ]:
# Ver qué hacemos con los NaN y convertir a INT creo que esta la tendremos que borrar porque no hay casi datos

datos['yearsincurrentrole'].unique()

yearsincurrentrole = datos['yearsincurrentrole'].str.replace(',0', '')


datos['yearsincurrentrole'] = yearsincurrentrole

datos['yearsincurrentrole'] 





0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611    NaN
1612    NaN
1613    NaN
Name: yearsincurrentrole, Length: 1614, dtype: object

In [ ]:
datos['yearssincelastpromotion'].unique()




datos[['yearssincelastpromotion']]


yearssincelastpromotion
0                          15
1                          11
2                          11
3                           5
4                           2
...                       ...
1609                        3
1610                        0
1611                        0
1612                        0
1613                        0

[1614 rows x 1 columns]

In [ ]:
# no tenemos que tocar nada

datos['yearswithcurrmanager'].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [ ]:
# esta ok

datos['datebirth'].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005],
      dtype=int64)

In [ ]:
#Tendremos que ver qué hacemos con los Nan

datos['remotework'].unique()
    


array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [ ]:
diccionario_mapa = {'Yes':'Yes', '1':'Yes', 'False':'No', '0':'No', 'True':'Yes'}

datos["remotework"] = datos["remotework"].map(diccionario_mapa)

datos['remotework'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'remotework'],
      dtype='object')

In [2]:
datos = pd.read_csv('Datos/datos_empresa.csv', index_col=0)
datos_limpios = pd.read_csv('Datos/datos_empresa_V1.csv', index_col=0)


In [3]:
#Creamos Dataframe de las columnas de los df a comparar

datos_col = pd.DataFrame(list(datos.columns), columns=['datos'])
datos_col
datos_limpio_col = pd.DataFrame(list(datos_limpios.columns), columns=['datos2'])
datos_limpio_col


datos2
0                        Age
1                  Attrition
2             BusinessTravel
3                  DailyRate
4                 Department
5           DistanceFromHome
6                  Education
7             EducationField
8             employeenumber
9    EnvironmentSatisfaction
10                    Gender
11                HourlyRate
12            JobInvolvement
13                  JobLevel
14                   JobRole
15           JobSatisfaction
16             MaritalStatus
17             MonthlyIncome
18               MonthlyRate
19        NUMCOMPANIESWORKED
20                  OverTime
21         PercentSalaryHike
22         PerformanceRating
23  RelationshipSatisfaction
24             StandardHours
25          StockOptionLevel
26         TOTALWORKINGYEARS
27     TrainingTimesLastYear
28           WORKLIFEBALANCE
29            YearsAtCompany
30        YearsInCurrentRole
31   YearsSinceLastPromotion
32      YEARSWITHCURRMANAGER
33                 DateBirth
34                RemoteWork

In [4]:
# mergeamos las columnas para saber si tenemos duplicados

df_merge = datos_col.merge(datos_limpio_col, left_on='datos', right_on='datos2', how = 'left')
df_merge




datos                    datos2
0                        Age                       Age
1                  Attrition                 Attrition
2             BusinessTravel            BusinessTravel
3                  DailyRate                 DailyRate
4                 Department                Department
5           DistanceFromHome          DistanceFromHome
6                  Education                 Education
7             EducationField            EducationField
8              employeecount                       NaN
9             employeenumber            employeenumber
10   EnvironmentSatisfaction   EnvironmentSatisfaction
11                    Gender                    Gender
12                HourlyRate                HourlyRate
13            JobInvolvement            JobInvolvement
14                  JobLevel                  JobLevel
15                   JobRole                   JobRole
16           JobSatisfaction           JobSatisfaction
17             MaritalStatus             MaritalStatus
18             MonthlyIncome             MonthlyIncome
19               MonthlyRate               MonthlyRate
20        NUMCOMPANIESWORKED        NUMCOMPANIESWORKED
21                    Over18                       NaN
22                  OverTime                  OverTime
23         PercentSalaryHike         PercentSalaryHike
24         PerformanceRating         PerformanceRating
25  RelationshipSatisfaction  RelationshipSatisfaction
26             StandardHours             StandardHours
27          StockOptionLevel          StockOptionLevel
28         TOTALWORKINGYEARS         TOTALWORKINGYEARS
29     TrainingTimesLastYear     TrainingTimesLastYear
30           WORKLIFEBALANCE           WORKLIFEBALANCE
31            YearsAtCompany            YearsAtCompany
32        YearsInCurrentRole        YearsInCurrentRole
33   YearsSinceLastPromotion   YearsSinceLastPromotion
34      YEARSWITHCURRMANAGER      YEARSWITHCURRMANAGER
35       SameAsMonthlyIncome                       NaN
36                 DateBirth                 DateBirth
37                    Salary                       NaN
38           RoleDepartament                       NaN
39            NUMBERCHILDREN                       NaN
40                RemoteWork                RemoteWork

In [5]:
#filtro para saber columnas que habíamos borrado

filtro = df_merge['datos2'].isna()
df_filtro = df_merge[filtro]

df_filtro

datos datos2
8         employeecount    NaN
21               Over18    NaN
35  SameAsMonthlyIncome    NaN
37               Salary    NaN
38      RoleDepartament    NaN
39       NUMBERCHILDREN    NaN

In [6]:
comparacion = df_merge['datos'] == df_merge['datos2']
comparacion

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21    False
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35    False
36     True
37    False
38    False
39    False
40     True
dtype: bool

In [7]:
#borramos columnas que no necesitamos

datos.drop( columns = ['employeecount','Over18','SameAsMonthlyIncome', 'Salary', 'RoleDepartament', 'NUMBERCHILDREN'], inplace= True)

In [8]:
# transformamos columnas para su mejor visulatización las convertimos todos a lower

new_columns = {column : column.lower() for column in datos}

new_columns

datos.rename(columns = new_columns, inplace= True)

datos.head()

age attrition businesstravel dailyrate                department  \
0  51        No            NaN    684,0$                       NaN   
1  52        No            NaN    699,0$                       NaN   
2  42        No  travel_rarely    532,0$   Research & Development    
3  47        No  travel_rarely    359,0$                       NaN   
4  46        No            NaN   1319,0$                       NaN   

   distancefromhome  education    educationfield employeenumber  \
0                 6          3               NaN          162,0   
1                 1          4     Life Sciences          259,0   
2                 4          2  Technical Degree          319,0   
3                 2          4           Medical            NaN   
4                 3          3  Technical Degree            NaN   

   environmentsatisfaction  gender hourlyrate  jobinvolvement  joblevel  \
0                        1       0         51               3         5   
1                        3       0         65               2         5   
2                        3       0         58               3         5   
3                        1       1         82               3         4   
4                        1       1         45               4         4   

               jobrole  jobsatisfaction maritalstatus monthlyincome  \
0   resEArch DIREcToR                 3           NaN       19537,0   
1             ManAGeR                 3           NaN       19999,0   
2             ManaGER                 4       Married       19232,0   
3   ReseArCH DIrECtOr                 3       Married       17169,0   
4     sAleS EXECUtIve                 1      Divorced           NaN   

   monthlyrate  numcompaniesworked overtime  percentsalaryhike  \
0         6462                   7       No                 13   
1         5678                   0      NaN                 14   
2         4933                   1       No                 11   
3        26703                   3      NaN                 19   
4         7739                   2       No                 12   

  performancerating  relationshipsatisfaction standardhours  stockoptionlevel  \
0               3,0                         3           NaN                 0   
1               3,0                         1           NaN                 1   
2               3,0                         4           NaN                 0   
3               3,0                         2           NaN                 2   
4               3,0                         4           NaN                 1   

  totalworkingyears  trainingtimeslastyear worklifebalance  yearsatcompany  \
0               NaN                      5             3,0              20   
1              34,0                      5             3,0              33   
2              22,0                      3             NaN              22   
3               NaN                      2             NaN              20   
4               NaN                      5             3,0              19   

  yearsincurrentrole  yearssincelastpromotion  yearswithcurrmanager  \
0                NaN                       15                    15   
1                NaN                       11                     9   
2                NaN                       11                    15   
3                NaN                        5                     6   
4                NaN                        2                     8   

   datebirth remotework  
0       1972        Yes  
1       1971          1  
2       1981          1  
3       1976      False  
4       1977          0

In [9]:
# Transformamos columnas

In [10]:
datos['age'].unique()

age = datos['age'].str.replace('fifty-eight', '58 ').str.replace('fifty-eight', '47 ').str.replace('thirty-six', '36').str.replace('fifty-five', '55').str.replace('fifty-two', '52').str.replace('thirty-one', '31').str.replace('twenty-six', '36').str.replace('thirty-seven', '37').str.replace('thirty-seven', '37').str.replace('thirty-two', '32').str.replace('twenty-four', '24').str.replace('forty-seven', '47').str.replace('thirty', '30')

datos['age'] = age

datos['age'].unique()

array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', '53', '43', '60', '32',
       '37', '49', '39', '50', '44', '30', '58 ', '29', '31', '54', '57',
       '27', '28', '26', '25', '24', '23', '22', '21', '20', '19', '18'],
      dtype=object)

In [11]:
datos['attrition'].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
businesstravel = datos['businesstravel'].str.replace('_', ' ').str.replace('-', ' ').str.capitalize()

datos['businesstravel'] = businesstravel

datos['businesstravel'].unique()



array([nan, 'Travel rarely', 'Travel frequently', 'Non travel'],
      dtype=object)

In [13]:
# nos falta ver qué hacemos con los Nan y convertirlo en INT. Llego hasta numcompaniesworked

dailyrate = datos['dailyrate'].str.replace('$', '')


datos['dailyrate'] = dailyrate

datos['dailyrate'] 

datos['businesstravel'].unique()


array([nan, 'Travel rarely', 'Travel frequently', 'Non travel'],
      dtype=object)

In [14]:
# ver qué hacemos con los Nan

datos['department'].unique()

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [38]:
# Hemos cambiado el tipo de int a str y elominado el menos de los negativos. Queda vovlerlo float.

datos_distance = datos['distancefromhome'].astype(str)

distancefromhome = datos_distance.str.replace('-', '')

datos['distancefromhome'] = distancefromhome

datos['distancefromhome'].unique()

array(['6', '1', '4', '2', '3', '22', '25', '9', '7', '23', '10', '12',
       '14', '13', '15', '8', '42', '28', '37', '5', '16', '35', '26',
       '24', '29', '17', '21', '18', '30', '27', '20', '31', '39', '11',
       '19', '33', '34', '46', '36', '45', '47', '32', '41', '49', '48',
       '38', '43', '40', '44'], dtype=object)

In [16]:
datos.head(1) # Llego hasta numcompaniesworked

age attrition businesstravel dailyrate department  distancefromhome  \
0  51        No            NaN     684,0        NaN                 6   

   education educationfield employeenumber  environmentsatisfaction  gender  \
0          3            NaN          162,0                        1       0   

  hourlyrate  jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0         51               3         5   resEArch DIREcToR                 3   

  maritalstatus monthlyincome  monthlyrate  numcompaniesworked overtime  \
0           NaN       19537,0         6462                   7       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   

  standardhours  stockoptionlevel totalworkingyears  trainingtimeslastyear  \
0           NaN                 0               NaN                      5   

  worklifebalance  yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0             3,0              20                NaN                       15   

   yearswithcurrmanager  datebirth remotework  
0                    15       1972        Yes

In [17]:
datos['education'].unique() # No hay que hacerle nada

array([3, 4, 2, 1, 5])

In [18]:
datos['educationfield'].unique() # ya está capitalizado. Nos falta ver que hacer con NaN

array([nan, 'Life Sciences', 'Technical Degree', 'Medical', 'Other',
       'Marketing', 'Human Resources'], dtype=object)

In [19]:
datos['employeenumber'].unique() # tiene NaN. Tiene duplicados

array(['162,0', '259,0', '319,0', ..., '2012,0', '2023,0', '2040,0'],
      dtype=object)

In [50]:
datos_duplicados = datos['employeenumber'][datos['employeenumber'].duplicated()].unique() # tomar la lista e iterar por ella para hacer la fusión. Documentar porque nos quedamos con los duplicados
datos_duplicados

array([nan, '1541,0', '1947,0', '1954,0', '307,0', '374,0', '524,0',
       '569,0', '1044,0', '1053,0', '1069,0', '1131,0', '1135,0',
       '1140,0', '1157,0', '1160,0', '1161,0', '1162,0', '1185,0',
       '1195,0', '1778,0', '1797,0', '1804,0', '1816,0', '1821,0',
       '1849,0', '1869,0', '1898,0', '1911,0', '1927,0', '423,0', '424,0',
       '433,0', '440,0', '447,0', '455,0', '460,0', '465,0', '470,0',
       '475,0', '478,0', '482,0', '495,0', '501,0', '502,0', '507,0',
       '517,0', '522,0', '523,0', '525,0', '526,0', '530,0', '544,0',
       '376,0', '381,0', '388,0', '389,0', '401,0', '416,0', '430,0',
       '438,0', '446,0', '448,0', '454,0', '458,0', '476,0', '483,0',
       '488,0', '500,0', '534,0', '586,0', '595,0', '608,0', '616,0',
       '621,0', '653,0', '663,0', '682,0', '710,0', '717,0', '721,0',
       '722,0', '724,0', '725,0', '728,0', '733,0', '734,0', '742,0',
       '747,0', '762,0', '783,0', '789,0', '793,0', '803,0', '809,0',
       '823,0', '842,0', '

In [51]:
datos['employeenumber'].duplicated().sum()

534

In [44]:
datos['employeenumber']

0        162,0
1        259,0
2        319,0
3          NaN
4          NaN
5       1900,0
6         81,0
7        387,0
8          NaN
9        999,0
10      1035,0
11         NaN
12         NaN
13        58,0
14         NaN
15       558,0
16       825,0
17         NaN
18         NaN
19         NaN
20      1712,0
21        73,0
22         NaN
23       820,0
24         NaN
25         NaN
26         NaN
27      1294,0
28         NaN
29      1774,0
30      1815,0
31      1993,0
32        32,0
33       100,0
34         NaN
35       244,0
36       327,0
37       373,0
38         NaN
39       729,0
40       830,0
41         NaN
42       981,0
43      1042,0
44      1080,0
45      1995,0
46       145,0
47       158,0
48       391,0
49       436,0
50         NaN
51      1527,0
52         NaN
53      1866,0
54      2026,0
55         NaN
56       107,0
57       170,0
58         NaN
59       215,0
60       304,0
61       529,0
62       691,0
63       692,0
64      1005,0
65      1024,0
66      10

In [20]:
datos['environmentsatisfaction'].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

In [21]:
datos['gender'].unique() # ¿queremos cambiar los 0 y uno por las iniciales del genero?

array([0, 1])

In [22]:
datos['hourlyrate'].unique() # pasar a int y antes cambiar el Not Avaiable a NaN

array(['51', '65', '58', '82', '45', '99', '91', '64', '55', '68', '49',
       '61', '79', '31', '69', '48', '80', '74', '98', '59', '33', '56',
       '66', '57', '53', '87', '81', '84', '32', '41', '92', '47',
       'Not Available', '43', '86', '30', '42', '88', '96', '67', '62',
       '72', '78', '89', '52', '50', '90', '37', '94', '76', '60', '46',
       '83', '100', '40', '97', '54', '75', '39', '85', '63', '44', '93',
       '36', '35', '73', '71', '70', '38', '77', '95', '34'], dtype=object)

In [23]:
datos['jobinvolvement'].unique() # no tocar

array([3, 2, 4, 1])

In [24]:
datos['joblevel'].unique() # no tocar

array([5, 4, 3, 2, 1])

In [25]:
# Todo pasado a minusculas, dejando la primera en mayusculas y eliminando los espacios que habia al inicio y final
datos['jobrole'] = datos['jobrole'].str.lower().str.title().str.strip()
datos['jobrole'].unique()

array(['Research Director', 'Manager', 'Sales Executive',
       'Manufacturing Director', 'Research Scientist',
       'Healthcare Representative', 'Laboratory Technician',
       'Sales Representative', 'Human Resources'], dtype=object)

In [26]:
datos['jobsatisfaction'].unique() # no tocar

array([3, 4, 1, 2])

In [27]:
# Sustituyo los que están mal escritos para que sean iguales a los que si creando un diccionario previamente.
replacements = {
    'divorced': 'Divorced',
    'Marreid': 'Married'
}

datos['maritalstatus'] = datos['maritalstatus'].replace(replacements)
datos['maritalstatus'].unique() 

array([nan, 'Married', 'Divorced', 'Single'], dtype=object)

In [28]:
datos['monthlyincome'].unique() # Tiene nan, hay que cambiarlo a NaN y pasarlo a float

array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841

In [29]:
datos['monthlyrate'].unique() # no tocar

array([ 6462,  5678,  4933, ..., 15302, 26956, 16642])

In [30]:
datos['numcompaniesworked'].unique() # no tocar

array([7, 0, 1, 3, 2, 4, 8, 9, 5, 6])

In [ ]:
# Función para convertir la coma en punto y los objet a float

columns = ['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'standardhours', 'stockoptionlevel', 'totalworkingyears',
       'trainingtimeslastyear', 'worklifebalance', 'yearsatcompany',
       'yearsincurrentrole', 'yearssincelastpromotion', 'yearswithcurrmanager',
       'datebirth', 'remotework']

performancerating = datos['performancerating'].str.replace(',', '.')

datos['performancerating'] = performancerating
datos['performancerating']

In [32]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'standardhours', 'stockoptionlevel', 'totalworkingyears',
       'trainingtimeslastyear', 'worklifebalance', 'yearsatcompany',
       'yearsincurrentrole', 'yearssincelastpromotion', 'yearswithcurrmanager',
       'datebirth', 'remotework'],
      dtype='object')

In [ ]:
# overtime mirar qué hacer con los nan

datos['overtime'].unique()

array(['No', nan, 'Yes'], dtype=object)

In [ ]:
# overtime mirar qué hacer con los nan

datos['overtime'].unique()

array(['No', nan, 'Yes'], dtype=object)

In [ ]:
datos['percentsalaryhike'].unique()



array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18],
      dtype=int64)

In [ ]:
#mirar que hacer con los nan y convertir a número porque es un objeto por las comas

suma = datos['performancerating'].value_counts()
print(suma)

performancerating = datos['performancerating'].str.replace(',0', '')


datos['performancerating'] = performancerating

datos['performancerating'] 



performancerating
3    1205
4     214
Name: count, dtype: int64


0         3
1         3
2         3
3         3
4         3
       ... 
1609    NaN
1610      3
1611      3
1612    NaN
1613      3
Name: performancerating, Length: 1614, dtype: object

In [ ]:
# No hacemos cambios de momento

datos['relationshipsatisfaction'].unique()



array([3, 1, 4, 2], dtype=int64)

In [ ]:
#borramos standard hours porque no tiene sentido tiene muchos nan y 80h es imposible
datos.drop( columns = ['standardhours'], inplace= True)




In [ ]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'remotework'],
      dtype='object')

In [ ]:
# No he hecho nada en esta columna parece estra bien
datos['stockoptionlevel'].unique()

array([0, 1, 2, 3], dtype=int64)

In [ ]:
# En cuanto gestionemos los nan cambiar a INT

datos['totalworkingyears'].unique()

totalworkingyears = datos['totalworkingyears'].str.replace(',0', '')


datos['totalworkingyears'] = totalworkingyears

datos['totalworkingyears'] 


0       NaN
1        34
2        22
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611      9
1612     12
1613    NaN
Name: totalworkingyears, Length: 1614, dtype: object

In [ ]:
# En cuanto gestionemos los nan cambiar a INT

datos['totalworkingyears'].unique()

array([nan, '34', '22', '28', '20', '21', '33', '40', '18', '25', '15',
       '17', '26', '16', '24', '14', '23', '27', '19', '11', '38', '37',
       '13', '12', '29', '10', '36', '35', '9', '31', '32', '8', '7',
       '30', '6', '5', '4', '3', '2', '1', '0'], dtype=object)

In [ ]:
# trainingtimeslastyear no hacer nada aparentemente toda la información es correcta

datos['trainingtimeslastyear'].unique()



array([5, 3, 2, 0, 1, 4, 6], dtype=int64)

In [ ]:
# Ver qué hacemos con los NaN y convertir a INT

datos['worklifebalance'].unique()

worklifebalance = datos['worklifebalance'].str.replace(',0', '')


datos['worklifebalance'] = worklifebalance

datos['worklifebalance'] 


0         3
1         3
2       NaN
3       NaN
4         3
       ... 
1609      3
1610      2
1611      3
1612      3
1613      3
Name: worklifebalance, Length: 1614, dtype: object

In [ ]:
# todo aparenta estar correcto

datos['yearsatcompany'].unique()



array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [ ]:
# Ver qué hacemos con los NaN y convertir a INT creo que esta la tendremos que borrar porque no hay casi datos

datos['yearsincurrentrole'].unique()

yearsincurrentrole = datos['yearsincurrentrole'].str.replace(',0', '')


datos['yearsincurrentrole'] = yearsincurrentrole

datos['yearsincurrentrole'] 





0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611    NaN
1612    NaN
1613    NaN
Name: yearsincurrentrole, Length: 1614, dtype: object

In [ ]:
datos['yearssincelastpromotion'].unique()




datos[['yearssincelastpromotion']]


yearssincelastpromotion
0                          15
1                          11
2                          11
3                           5
4                           2
...                       ...
1609                        3
1610                        0
1611                        0
1612                        0
1613                        0

[1614 rows x 1 columns]

In [ ]:
# no tenemos que tocar nada

datos['yearswithcurrmanager'].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [ ]:
# esta ok

datos['datebirth'].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005],
      dtype=int64)

In [ ]:
#Tendremos que ver qué hacemos con los Nan

datos['remotework'].unique()
    


array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [ ]:
diccionario_mapa = {'Yes':'Yes', '1':'Yes', 'False':'No', '0':'No', 'True':'Yes'}

datos["remotework"] = datos["remotework"].map(diccionario_mapa)

datos['remotework'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'remotework'],
      dtype='object')

In [ ]:
datos['percentsalaryhike'].unique()



array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18],
      dtype=int64)

In [ ]:
#mirar que hacer con los nan y convertir a número porque es un objeto por las comas

suma = datos['performancerating'].value_counts()
print(suma)

performancerating = datos['performancerating'].str.replace(',0', '')


datos['performancerating'] = performancerating

datos['performancerating'] 



performancerating
3    1205
4     214
Name: count, dtype: int64


0         3
1         3
2         3
3         3
4         3
       ... 
1609    NaN
1610      3
1611      3
1612    NaN
1613      3
Name: performancerating, Length: 1614, dtype: object

In [ ]:
# No hacemos cambios de momento

datos['relationshipsatisfaction'].unique()



array([3, 1, 4, 2], dtype=int64)

In [ ]:
#borramos standard hours porque no tiene sentido tiene muchos nan y 80h es imposible
datos.drop( columns = ['standardhours'], inplace= True)




In [ ]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'remotework'],
      dtype='object')

In [ ]:
# No he hecho nada en esta columna parece estra bien
datos['stockoptionlevel'].unique()

array([0, 1, 2, 3], dtype=int64)

In [ ]:
# En cuanto gestionemos los nan cambiar a INT

datos['totalworkingyears'].unique()

totalworkingyears = datos['totalworkingyears'].str.replace(',0', '')


datos['totalworkingyears'] = totalworkingyears

datos['totalworkingyears'] 


0       NaN
1        34
2        22
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611      9
1612     12
1613    NaN
Name: totalworkingyears, Length: 1614, dtype: object

In [ ]:
# En cuanto gestionemos los nan cambiar a INT

datos['totalworkingyears'].unique()

array([nan, '34', '22', '28', '20', '21', '33', '40', '18', '25', '15',
       '17', '26', '16', '24', '14', '23', '27', '19', '11', '38', '37',
       '13', '12', '29', '10', '36', '35', '9', '31', '32', '8', '7',
       '30', '6', '5', '4', '3', '2', '1', '0'], dtype=object)

In [ ]:
# trainingtimeslastyear no hacer nada aparentemente toda la información es correcta

datos['trainingtimeslastyear'].unique()



array([5, 3, 2, 0, 1, 4, 6], dtype=int64)

In [ ]:
# Ver qué hacemos con los NaN y convertir a INT

datos['worklifebalance'].unique()

worklifebalance = datos['worklifebalance'].str.replace(',0', '')


datos['worklifebalance'] = worklifebalance

datos['worklifebalance'] 


0         3
1         3
2       NaN
3       NaN
4         3
       ... 
1609      3
1610      2
1611      3
1612      3
1613      3
Name: worklifebalance, Length: 1614, dtype: object

In [ ]:
# todo aparenta estar correcto

datos['yearsatcompany'].unique()



array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [ ]:
# Ver qué hacemos con los NaN y convertir a INT creo que esta la tendremos que borrar porque no hay casi datos

datos['yearsincurrentrole'].unique()

yearsincurrentrole = datos['yearsincurrentrole'].str.replace(',0', '')


datos['yearsincurrentrole'] = yearsincurrentrole

datos['yearsincurrentrole'] 





0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611    NaN
1612    NaN
1613    NaN
Name: yearsincurrentrole, Length: 1614, dtype: object

In [ ]:
datos['yearssincelastpromotion'].unique()




datos[['yearssincelastpromotion']]


yearssincelastpromotion
0                          15
1                          11
2                          11
3                           5
4                           2
...                       ...
1609                        3
1610                        0
1611                        0
1612                        0
1613                        0

[1614 rows x 1 columns]

In [ ]:
# no tenemos que tocar nada

datos['yearswithcurrmanager'].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [ ]:
# esta ok

datos['datebirth'].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005],
      dtype=int64)

In [ ]:
#Tendremos que ver qué hacemos con los Nan

datos['remotework'].unique()
    


array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [ ]:
diccionario_mapa = {'Yes':'Yes', '1':'Yes', 'False':'No', '0':'No', 'True':'Yes'}

datos["remotework"] = datos["remotework"].map(diccionario_mapa)

datos['remotework'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
datos.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'overtime',
       'percentsalaryhike', 'performancerating', 'relationshipsatisfaction',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager', 'datebirth',
       'remotework'],
      dtype='object')